echo "Reading ~/.bashrc"

# Initialize FINK if needed

if [[ ! -x $(which fink) && -d /sw/bin ]];then
	source /sw/bin/init.sh
fi



# Set the DISPLAY variable -- works for Apple X11 with Fast User Switching

if [[ -z $DISPLAY && -z $SSH_CONNECTION ]]; then
    disp_no=($( ps -awx | grep -F X11.app | awk '{print $NF}' | grep -e ":[0-9]"  ))
    if [[ -n $disp_no ]];then
        export DISPLAY=${disp_no}.0
    else
        export DISPLAY=:0.0
    fi
    echo "DISPLAY has been set to $DISPLAY"
fi


# iTerm Tab and Title Customization and prompt customization

# Put the string " [bash]   hostname::/full/directory/path"
# in the title bar using the command sequence
# \[\e]2;[bash]   \h::\]$PWD\[\a\]

# Put the penultimate and current directory 
# in the iterm tab
# \[\e]1;\]$(basename $(dirname $PWD))/\W\[\a\]

# Make a simple command-line prompt:  bash-$

PS1=$'\[\e]2;[bash]   \h::\]$PWD\[\a\]\[\e]1;\]$(basename $(dirname $PWD))/\W\[\a\]bash-\$ '


F77=g95; export F77
FC=g95; export FC
F90=g95; export F90

export CC=gcc-4.2
export CXX=g++-4.2

export LC_ALL=C

export CFLAGS=-O3
export LDFLAGS=-static

export INCLUDEFFTW=/usr/local/include/fftw

PATH=/bin:/usr/bin:/usr/local/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/X11/bin:/sw/bin

export PATH

